import "@/styles/globals.css";

import type { Metadata } from "next";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

import SharedLayout from "@/components/layout";
import { ThemeProvider } from "@/components/theme-provider";
import { wagmiConfig } from "@/config";
import { ContextProvider } from "@/context";
import { noto_sans } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie"),
  );
  return (
    <html lang="en">
      <body className={noto_sans.className}>
        <div vaul-drawer-wrapper="">
          <ContextProvider initialState={initialState}>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem={false}
              forcedTheme="light"
            >
              <SharedLayout>{children}</SharedLayout>
            </ThemeProvider>
          </ContextProvider>
        </div>
      </body>
    </html>
  );
}
