import "@/styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SharedLayout from "@/components/layout";
import Providers from "@/providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SharedLayout>{children}</SharedLayout>
        </Providers>
      </body>
    </html>
  );
}
